name: Links

on:
  push:
    paths:
      - ".github/workflows/**"
      - "**.md"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: lycheeverse/lychee-action@v1.3.0
        with:
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
